apiVersion: v1
kind: Service
metadata:
  name: jjhg-api-service-nodeport
spec:
  type: NodePort
  selector:
    app: jjhg-api
  ports:
  - protocol: TCP
    port: 8080  # Service ip port, for internal use, like clusterIp type
    nodePort: 30100 # Open port on all nodes, must be > 30000, will listen on 0.0.0.0
    targetPort: 4000 # Port on target pods